# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: Travis
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Transport management system
repo_name: tms
repo_slug: tms
repo_website: https://github.com/OCA/tms
travis_apt_packages: []
travis_apt_sources: []
