from . import tms_analytic
from . import tms_goods
from . import tms_package
from . import tms_equipment
from . import project_task_checkpoint
from . import account_analytic_line
from . import account_move_line
from . import fleet_vehicle
from . import fleet_vehicle_model
from . import stock_rule
from . import product_template
from . import project_project
from . import project_task
from . import res_config_settings
from . import purchase
from . import res_partner
from . import sale_order
from . import sale_order_line
